name: flutter_cache_pro
description: "For cashing REST API"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true